- model_name: "ch_chinese_cht_en_japan_ppocr_v5-r20250912"
  config_file: ":/ch_chinese_cht_en_japan_ppocr_v5.yaml"
- model_name: "ch_ppocr_v4-r20230915"
  config_file: ":/ch_ppocr_v4.yaml"
- model_name: "clrnet_tusimple_r18-r20230901"
  config_file: ":/clrnet_tusimple_r18.yaml"
- model_name: "damo_yolo_l-r20231001"
  config_file: ":/damo_yolo_l.yaml"
- model_name: "damo_yolo_m-r20231001"
  config_file: ":/damo_yolo_m.yaml"
- model_name: "damo_yolo_s-r20231001"
  config_file: ":/damo_yolo_s.yaml"
- model_name: "damo_yolo_t-r20231001"
  config_file: ":/damo_yolo_t.yaml"
- model_name: "deimv2_hgnetv2_n_coco-r20251001"
  config_file: ":/deimv2_hgnetv2_n_coco.yaml"
- model_name: "deimv2_dinov3_s_coco-r20251001"
  config_file: ":/deimv2_dinov3_s_coco.yaml"
- model_name: "deimv2_dinov3_m_coco-r20251001"
  config_file: ":/deimv2_dinov3_m_coco.yaml"
- model_name: "depth_anything_v2_vit_b-r20240721"
  config_file: ":/depth_anything_v2_vit_b.yaml"
- model_name: "depth_anything_v2_vit_l-r20240721"
  config_file: ":/depth_anything_v2_vit_l.yaml"
- model_name: "depth_anything_v2_vit_s-r20240721"
  config_file: ":/depth_anything_v2_vit_s.yaml"
- model_name: "depth_anything_vit_b-r20240124"
  config_file: ":/depth_anything_vit_b.yaml"
- model_name: "depth_anything_vit_l-r20240124"
  config_file: ":/depth_anything_vit_l.yaml"
- model_name: "depth_anything_vit_s-r20240124"
  config_file: ":/depth_anything_vit_s.yaml"
- model_name: "dfine_l_obj2coco-r20250514"
  config_file: ":/dfine_l_obj2coco.yaml"
- model_name: "dfine_m_obj2coco-r20250514"
  config_file: ":/dfine_m_obj2coco.yaml"
- model_name: "dfine_s_obj2coco-r20250514"
  config_file: ":/dfine_s_obj2coco.yaml"
- model_name: "dfine_x_obj2coco-r20250514"
  config_file: ":/dfine_x_obj2coco.yaml"
- model_name: "doclayout_yolo-r20241024"
  config_file: ":/doclayout_yolo.yaml"
- model_name: "edge_sam_with_chinese_clip-r20240131"
  config_file: ":/edge_sam_with_chinese_clip.yaml"
- model_name: "edge_sam-r20231213"
  config_file: ":/edge_sam.yaml"
- model_name: "efficientvit_sam_l0_vit_h-r20230920"
  config_file: ":/efficientvit_sam_l0_vit_h.yaml"
- model_name: "efficientvit_sam_l1_vit_h-r20230920"
  config_file: ":/efficientvit_sam_l1_vit_h.yaml"
- model_name: "florence2_large_ft"
  config_file: ":/florence2_large_ft.yaml"
- model_name: "geco_sam_hq_vit_h-r20250330"
  config_file: ":/geco_sam_hq_vit_h.yaml"
- model_name: "gold_yolo_l-r20231001"
  config_file: ":/gold_yolo_l.yaml"
- model_name: "gold_yolo_m-r20231001"
  config_file: ":/gold_yolo_m.yaml"
- model_name: "gold_yolo_n-r20231001"
  config_file: ":/gold_yolo_n.yaml"
- model_name: "gold_yolo_s-r20231001"
  config_file: ":/gold_yolo_s.yaml"
- model_name: "grounding_dino_api-r20250415"
  config_file: ":/grounding_dino_api.yaml"
- model_name: "groundingdino_swint_ogc_quant-r20231024"
  config_file: ":/groundingdino_swint_ogc_quant.yaml"
- model_name: "groundingdino_swint_sam2_large-r20240806"
  config_file: ":/groundingdino_swint_sam2_large.yaml"
- model_name: "groundingdino_swinb_cogcoor_quant-r20231024"
  config_file: ":/groundingdino_swinb_cogcoor_quant.yaml"
- model_name: "hyper_yolos-r20241216"
  config_file: ":/hyper_yolos.yaml"
- model_name: "hyper_yolos_seg-r20241216"
  config_file: ":/hyper_yolos_seg.yaml"
- model_name: "internimage_l_22kto1k_384-r20230520"
  config_file: ":/internimage_l_22kto1k_384.yaml"
- model_name: "japan_ppocr-r20240803"
  config_file: ":/japan_ppocr.yaml"
- model_name: "mobile_sam_vit_h-r20230810"
  config_file: ":/mobile_sam_vit_h.yaml"
- model_name: "open_vision-r20241010"
  config_file: ":/open_vision.yaml"
- model_name: "pulc_person_attribute-r20231111"
  config_file: ":/pulc_person_attribute.yaml"
- model_name: "pulc_vehicle_attribute-r20231111"
  config_file: ":/pulc_vehicle_attribute.yaml"
- model_name: "ram_plus_swin_large_14m-r20240728"
  config_file: ":/ram_plus_swin_large_14m.yaml"
- model_name: "ram_swin_large_14m-r20231024"
  config_file: ":/ram_swin_large_14m.yaml"
- model_name: "remote_server-r20251101"
  config_file: ":/remote_server.yaml"
- model_name: "rfdetr_base_coco-r20250426"
  config_file: ":/rfdetr_base_coco.yaml"
- model_name: "rfdetr_base-r20250426"
  config_file: ":/rfdetr_base.yaml"
- model_name: "rfdetr_large-r20250426"
  config_file: ":/rfdetr_large.yaml"
- model_name: "rfdetr_medium-r20250814"
  config_file: ":/rfdetr_medium.yaml"
- model_name: "rfdetr_nano-r20250814"
  config_file: ":/rfdetr_nano.yaml"
- model_name: "rfdetr_seg_preview-r20251104"
  config_file: ":/rfdetr_seg_preview.yaml"
- model_name: "rfdetr_small-r20250814"
  config_file: ":/rfdetr_small.yaml"
- model_name: "rmbg_v14-r20240908"
  config_file: ":/rmbg_v14.yaml"
- model_name: "rmbg_v20_quant-r20250530"
  config_file: ":/rmbg_v20_quant.yaml"
- model_name: "rmbg_v20-r20250530"
  config_file: ":/rmbg_v20.yaml"
- model_name: "rtdetr_l-r20250517"
  config_file: ":/rtdetr_l.yaml"
- model_name: "rtdetr_r50-r20230520"
  config_file: ":/rtdetr_r50.yaml"
- model_name: "rtdetr_x-r20250517"
  config_file: ":/rtdetr_x.yaml"
- model_name: "rtdetrv2l-r20240730"
  config_file: ":/rtdetrv2l.yaml"
- model_name: "rtdetrv2m-r20240730"
  config_file: ":/rtdetrv2m.yaml"
- model_name: "rtdetrv2m7x-r20240730"
  config_file: ":/rtdetrv2m7x.yaml"
- model_name: "rtdetrv2s-r20240730"
  config_file: ":/rtdetrv2s.yaml"
- model_name: "rtdetrv2x-r20240730"
  config_file: ":/rtdetrv2x.yaml"
- model_name: "rtmdet_m_coco_person_rtmo_m-r20240112"
  config_file: ":/rtmdet_m_coco_person_rtmo_m.yaml"
- model_name: "sam_hq_vit_b-r20231111"
  config_file: ":/sam_hq_vit_b.yaml"
- model_name: "sam_hq_vit_h_quant-r20231111"
  config_file: ":/sam_hq_vit_h_quant.yaml"
- model_name: "sam_hq_vit_l_quant-r20231111"
  config_file: ":/sam_hq_vit_l_quant.yaml"
- model_name: "sam_hq_vit_l-r20231111"
  config_file: ":/sam_hq_vit_l.yaml"
- model_name: "sam_med2d_vit_b-r20230901"
  config_file: ":/sam_med2d_vit_b.yaml"
- model_name: "sam2_hiera_base_video-r20240901"
  config_file: ":/sam2_hiera_base_video.yaml"
- model_name: "sam2_hiera_base-r20240801"
  config_file: ":/sam2_hiera_base.yaml"
- model_name: "sam2_hiera_large_video-r20240901"
  config_file: ":/sam2_hiera_large_video.yaml"
- model_name: "sam2_hiera_large-r20240801"
  config_file: ":/sam2_hiera_large.yaml"
- model_name: "sam2_hiera_small_video-r20240901"
  config_file: ":/sam2_hiera_small_video.yaml"
- model_name: "sam2_hiera_small-r20240801"
  config_file: ":/sam2_hiera_small.yaml"
- model_name: "sam2_hiera_tiny_video-r20240901"
  config_file: ":/sam2_hiera_tiny_video.yaml"
- model_name: "sam2_hiera_tiny-r20240801"
  config_file: ":/sam2_hiera_tiny.yaml"
- model_name: "segment_anything_vit_b_quant-r20230810"
  config_file: ":/segment_anything_vit_b_quant.yaml"
- model_name: "segment_anything_vit_b-r20230810"
  config_file: ":/segment_anything_vit_b.yaml"
- model_name: "segment_anything_vit_h_quant-r20230810"
  config_file: ":/segment_anything_vit_h_quant.yaml"
- model_name: "segment_anything_vit_l_quant-r20230810"
  config_file: ":/segment_anything_vit_l_quant.yaml"
- model_name: "segment_anything_vit_l-r20230810"
  config_file: ":/segment_anything_vit_l.yaml"
- model_name: "upn-r20241128"
  config_file: ":/upn.yaml"
- model_name: "yolo_nas_l-r20230615"
  config_file: ":/yolo_nas_l.yaml"
- model_name: "yolo_nas_m-r20230615"
  config_file: ":/yolo_nas_m.yaml"
- model_name: "yolo_nas_s-r20230615"
  config_file: ":/yolo_nas_s.yaml"
- model_name: "yolo11s_cls-r20240930"
  config_file: ":/yolo11s_cls.yaml"
- model_name: "yolo11s_det_botsort-r20240930"
  config_file: ":/yolo11s_det_botsort.yaml"
- model_name: "yolo11s_obb_botsort-r20240930"
  config_file: ":/yolo11s_obb_botsort.yaml"
- model_name: "yolo11s_obb-r20240930"
  config_file: ":/yolo11s_obb.yaml"
- model_name: "yolo11s_pose_botsort-r20240930"
  config_file: ":/yolo11s_pose_botsort.yaml"
- model_name: "yolo11s_pose-r20240930"
  config_file: ":/yolo11s_pose.yaml"
- model_name: "yolo11s_seg_botsort-r20240930"
  config_file: ":/yolo11s_seg_botsort.yaml"
- model_name: "yolo11s_seg-r20240930"
  config_file: ":/yolo11s_seg.yaml"
- model_name: "yolo11s-r20240930"
  config_file: ":/yolo11s.yaml"
- model_name: "yolo12l-r20250514"
  config_file: ":/yolo12l.yaml"
- model_name: "yolo12m-r20250514"
  config_file: ":/yolo12m.yaml"
- model_name: "yolo12n-r20250514"
  config_file: ":/yolo12n.yaml"
- model_name: "yolo12s-r20250514"
  config_file: ":/yolo12s.yaml"
- model_name: "yolo12x-r20250514"
  config_file: ":/yolo12x.yaml"
- model_name: "yoloe_11s-r20250524"
  config_file: ":/yoloe_11s.yaml"
- model_name: "yoloe_v8l-r20250524"
  config_file: ":/yoloe_v8l.yaml"
- model_name: "yolov5_car_plate-r20230112"
  config_file: ":/yolov5_car_plate.yaml"
- model_name: "yolov5l-r20230520"
  config_file: ":/yolov5l.yaml"
- model_name: "yolov5m_obb_csl_dotav15-r20231024"
  config_file: ":/yolov5m_obb_csl_dotav15.yaml"
- model_name: "yolov5m_obb_csl_dotav20-r20231024"
  config_file: ":/yolov5m_obb_csl_dotav20.yaml"
- model_name: "yolov5m_ram-r20231101"
  config_file: ":/yolov5m_ram.yaml"
- model_name: "yolov5m-r20230520"
  config_file: ":/yolov5m.yaml"
- model_name: "yolov5n_obb_drone_vehicle-r20231024"
  config_file: ":/yolov5n_obb_drone_vehicle.yaml"
- model_name: "yolov5n-r20230520"
  config_file: ":/yolov5n.yaml"
- model_name: "yolov5s_cls-r20231220"
  config_file: ":/yolov5s_cls.yaml"
- model_name: "yolov5s_det_botsort-r20240816"
  config_file: ":/yolov5s_det_botsort.yaml"
- model_name: "yolov5s_mobile_sam_vit_h-r20230920"
  config_file: ":/yolov5s_mobile_sam_vit_h.yaml"
- model_name: "yolov5s_obb_csl_dotav10-r20231024"
  config_file: ":/yolov5s_obb_csl_dotav10.yaml"
- model_name: "yolov5s_resnet50-r20230520"
  config_file: ":/yolov5s_resnet50.yaml"
- model_name: "yolov5s_sahi-r20241118"
  config_file: ":/yolov5s_sahi.yaml"
- model_name: "yolov5s_seg-r20231027"
  config_file: ":/yolov5s_seg.yaml"
- model_name: "yolov5s-r20230520"
  config_file: ":/yolov5s.yaml"
- model_name: "yolov5x-r20230520"
  config_file: ":/yolov5x.yaml"
- model_name: "yolov6l_mbla-r20230520"
  config_file: ":/yolov6l_mbla.yaml"
- model_name: "yolov6lite_l_face-r20230520"
  config_file: ":/yolov6lite_l_face.yaml"
- model_name: "yolov6lite_m_face-r20230520"
  config_file: ":/yolov6lite_m_face.yaml"
- model_name: "yolov6lite_s_face-r20230520"
  config_file: ":/yolov6lite_s_face.yaml"
- model_name: "yolov6m_mbla-r20230520"
  config_file: ":/yolov6m_mbla.yaml"
- model_name: "yolov6s_mbla-r20230520"
  config_file: ":/yolov6s_mbla.yaml"
- model_name: "yolov6s-r20230520"
  config_file: ":/yolov6s.yaml"
- model_name: "yolov6s6-r20230520"
  config_file: ":/yolov6s6.yaml"
- model_name: "yolov6x_mbla-r20230520"
  config_file: ":/yolov6x_mbla.yaml"
- model_name: "yolov7-r20230520"
  config_file: ":/yolov7.yaml"
- model_name: "yolov8l_oiv7-r20240529"
  config_file: ":/yolov8l_oiv7.yaml"
- model_name: "yolov8l_seg-r20230620"
  config_file: ":/yolov8l_seg.yaml"
- model_name: "yolov8l_worldv2_cc3m-r20240529"
  config_file: ":/yolov8l_worldv2_cc3m.yaml"
- model_name: "yolov8l_worldv2-r20240529"
  config_file: ":/yolov8l_worldv2.yaml"
- model_name: "yolov8l-r20230520"
  config_file: ":/yolov8l.yaml"
- model_name: "yolov8m_oiv7-r20240529"
  config_file: ":/yolov8m_oiv7.yaml"
- model_name: "yolov8m_seg_bytetrack-r20240816"
  config_file: ":/yolov8m_seg_bytetrack.yaml"
- model_name: "yolov8m_seg-r20230620"
  config_file: ":/yolov8m_seg.yaml"
- model_name: "yolov8m_worldv2-r20240529"
  config_file: ":/yolov8m_worldv2.yaml"
- model_name: "yolov8m-r20230520"
  config_file: ":/yolov8m.yaml"
- model_name: "yolov8n_obb_botsort-r20240816"
  config_file: ":/yolov8n_obb_botsort.yaml"
- model_name: "yolov8n_oiv7-r20240529"
  config_file: ":/yolov8n_oiv7.yaml"
- model_name: "yolov8n_pose-r20231103"
  config_file: ":/yolov8n_pose.yaml"
- model_name: "yolov8n_seg-r20230620"
  config_file: ":/yolov8n_seg.yaml"
- model_name: "yolov8n-r20230520"
  config_file: ":/yolov8n.yaml"
- model_name: "yolov8s_cls-r20231220"
  config_file: ":/yolov8s_cls.yaml"
- model_name: "yolov8s_det_botsort-r20240816"
  config_file: ":/yolov8s_det_botsort.yaml"
- model_name: "yolov8s_obb-r20240111"
  config_file: ":/yolov8s_obb.yaml"
- model_name: "yolov8s_oiv7-r20240529"
  config_file: ":/yolov8s_oiv7.yaml"
- model_name: "yolov8s_sahi-r20231008"
  config_file: ":/yolov8s_sahi.yaml"
- model_name: "yolov8s_sam2_hiera_base-r20250218"
  config_file: ":/yolov8s_sam2_hiera_base.yaml"
- model_name: "yolov8s_seg-r20230620"
  config_file: ":/yolov8s_seg.yaml"
- model_name: "yolov8s_worldv2_ram_plus-r20240529"
  config_file: ":/yolov8s_worldv2_ram_plus.yaml"
- model_name: "yolov8s_worldv2-r20240529"
  config_file: ":/yolov8s_worldv2.yaml"
- model_name: "yolov8s-r20230520"
  config_file: ":/yolov8s.yaml"
- model_name: "yolov8x_oiv7-r20240529"
  config_file: ":/yolov8x_oiv7.yaml"
- model_name: "yolov8x_pose_p6_botsort-r20240816"
  config_file: ":/yolov8x_pose_p6_botsort.yaml"
- model_name: "yolov8x_pose_p6-r20231103"
  config_file: ":/yolov8x_pose_p6.yaml"
- model_name: "yolov8x_seg-r20230620"
  config_file: ":/yolov8x_seg.yaml"
- model_name: "yolov8x_worldv2-r20240529"
  config_file: ":/yolov8x_worldv2.yaml"
- model_name: "yolov8x-r20230520"
  config_file: ":/yolov8x.yaml"
- model_name: "yolov8x6_oiv7-r20240529"
  config_file: ":/yolov8x6_oiv7.yaml"
- model_name: "yolov9_gelan_c-r20240224"
  config_file: ":/yolov9_gelan_c.yaml"
- model_name: "yolov9_gelan_e-r20240224"
  config_file: ":/yolov9_gelan_e.yaml"
- model_name: "yolov9c-r20240224"
  config_file: ":/yolov9c.yaml"
- model_name: "yolov9e-r20240224"
  config_file: ":/yolov9e.yaml"
- model_name: "yolov10b-r20240525"
  config_file: ":/yolov10b.yaml"
- model_name: "yolov10l-r20240525"
  config_file: ":/yolov10l.yaml"
- model_name: "yolov10m-r20240525"
  config_file: ":/yolov10m.yaml"
- model_name: "yolov10n-r20240525"
  config_file: ":/yolov10n.yaml"
- model_name: "yolov10s-r20240525"
  config_file: ":/yolov10s.yaml"
- model_name: "yolov10x-r20240525"
  config_file: ":/yolov10x.yaml"
- model_name: "yolox_l_dwpose_ucoco-r20230820"
  config_file: ":/yolox_l_dwpose_ucoco.yaml"
- model_name: "yolox_s-r20230520"
  config_file: ":/yolox_s.yaml"