type: sam_hq
name: sam_hq_vit_h_quant-r20231111
provider: ETH ZÃ¼rich
display_name: SAM-HQ (ViT-Huge Quant)
encoder_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.0.0/sam_hq_vit_h_encoder_quant.onnx
decoder_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.0.0/sam_hq_vit_h_decoder.onnx
input_size: 1024
max_width: 1024
max_height: 682
