type: grounding_dino
name: groundingdino_swinb_cogcoor_quant-r20231024
provider: IDEA-Research
display_name: GroundingDINO (SwinB-QInt8)
model_type: groundingdino_swinb_cogcoor
model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v1.0.0/groundingdino_swinb_cogcoor_quant.onnx
input_width: 1200
input_height: 800
conf_threshold: 0.30
text_threshold: 0.25