- model_name: "ch_ppocr_v4-r20230915"
  config_file: ":/ch_ppocr_v4.yaml"
- model_name: "efficientvit_sam_l0_vit_h-r20230920"
  config_file: ":/efficientvit_sam_l0_vit_h.yaml"
- model_name: "efficientvit_sam_l1_vit_h-r20230920"
  config_file: ":/efficientvit_sam_l1_vit_h.yaml"
- model_name: "yolov5m_bytetrack-r20230925"
  config_file: ":/yolov5m_bytetrack.yaml"
- model_name: "yolov5s_mobile_sam_vit_h-r20230920"
  config_file: ":/yolov5s_mobile_sam_vit_h.yaml"
- model_name: "sam_med2d_vit_b-r20230901"
  config_file: ":/sam_med2d_vit_b.yaml"
- model_name: "segment_anything_vit_b_quant-r20230810"
  config_file: ":/segment_anything_vit_b_quant.yaml"
- model_name: "segment_anything_vit_b-r20230810"
  config_file: ":/segment_anything_vit_b.yaml"
- model_name: "segment_anything_vit_l_quant-r20230810"
  config_file: ":/segment_anything_vit_l_quant.yaml"
- model_name: "segment_anything_vit_l-r20230810"
  config_file: ":/segment_anything_vit_l.yaml"
- model_name: "segment_anything_vit_h_quant-r20230810"
  config_file: ":/segment_anything_vit_h_quant.yaml"
- model_name: "lvm_sam_ssk_buid_vit_b-r20230810"
  config_file: ":/lvm_sam_ssk_buid_vit_b.yaml"
- model_name: "lvm_sam_ssk_isic_vit_b-r20230810"
  config_file: ":/lvm_sam_ssk_isic_vit_b.yaml"
- model_name: "lvm_sam_ssk_kvasir_vit_b-r20230810"
  config_file: ":/lvm_sam_ssk_kvasir_vit_b.yaml"
- model_name: "medsam_vit_b-r20230810"
  config_file: ":/medsam_vit_b.yaml"
- model_name: "mobile_sam_vit_h-r20230810"
  config_file: ":/mobile_sam_vit_h.yaml"
- model_name: "clrnet_tusimple_r18-r20230901"
  config_file: ":/clrnet_tusimple_r18.yaml"
- model_name: "yolox_l_dwpose_ucoco-r20230820"
  config_file: ":/yolox_l_dwpose_ucoco.yaml"
- model_name: "rtdetr_r50-r20230520"
  config_file: ":/rtdetr_r50.yaml"
- model_name: "yolov5s_resnet50-r20230520"
  config_file: ":/yolov5s_resnet50.yaml"
- model_name: "yolov5n-r20230520"
  config_file: ":/yolov5n.yaml"
- model_name: "yolov5s-r20230520"
  config_file: ":/yolov5s.yaml"
- model_name: "yolov5m-r20230520"
  config_file: ":/yolov5m.yaml"
- model_name: "yolov5l-r20230520"
  config_file: ":/yolov5l.yaml"
- model_name: "yolov5x-r20230520"
  config_file: ":/yolov5x.yaml"
- model_name: "yolov6s-r20230520"
  config_file: ":/yolov6s.yaml"
- model_name: "yolov6s6-r20230520"
  config_file: ":/yolov6s6.yaml"
- model_name: "yolov6s_mbla-r20230520"
  config_file: ":/yolov6s_mbla.yaml"
- model_name: "yolov6m_mbla-r20230520"
  config_file: ":/yolov6m_mbla.yaml"
- model_name: "yolov6l_mbla-r20230520"
  config_file: ":/yolov6l_mbla.yaml"
- model_name: "yolov6x_mbla-r20230520"
  config_file: ":/yolov6x_mbla.yaml"
- model_name: "yolov6lite_s_face-r20230520"
  config_file: ":/yolov6lite_s_face.yaml"
- model_name: "yolov7-r20230520"
  config_file: ":/yolov7.yaml"
- model_name: "yolov8n-r20230520"
  config_file: ":/yolov8n.yaml"
- model_name: "yolov8s-r20230520"
  config_file: ":/yolov8s.yaml"
- model_name: "yolov8m-r20230520"
  config_file: ":/yolov8m.yaml"
- model_name: "yolov8l-r20230520"
  config_file: ":/yolov8l.yaml"
- model_name: "yolov8x-r20230520"
  config_file: ":/yolov8x.yaml"
- model_name: "yolov8n-seg-r20230620"
  config_file: ":/yolov8n_seg.yaml"
- model_name: "yolov8s-seg-r20230620"
  config_file: ":/yolov8s_seg.yaml"
- model_name: "yolov8m-seg-r20230620"
  config_file: ":/yolov8m_seg.yaml"
- model_name: "yolov8l-seg-r20230620"
  config_file: ":/yolov8l_seg.yaml"
- model_name: "yolov8x-seg-r20230620"
  config_file: ":/yolov8x_seg.yaml"
- model_name: "yolox-r20230520"
  config_file: ":/yolox_s.yaml"
- model_name: "yolo-nas-s-r20230615"
  config_file: ":/yolo_nas_s.yaml"
- model_name: "yolo-nas-m-r20230615"
  config_file: ":/yolo_nas_m.yaml"
- model_name: "yolo-nas-l-r20230615"
  config_file: ":/yolo_nas_l.yaml"