type: segment_anything_2
name: sam2_hiera_small-r20240801
provider: Meta
display_name: Segment Anything 2.1 (Small)
encoder_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.5.0/sam2.1_hiera_small.encoder.onnx
decoder_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.5.0/sam2.1_hiera_small.decoder.onnx
epsilon: 0.001
padding_ratio: 0.2