type: segment_anything
name: segment_anything_vit_l_quant-r20230810
provider: Meta
display_name: Segment Anything (ViT-Large Quant)
encoder_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v0.2.0/sam_vit_l_0b3195.encoder.quant.onnx
decoder_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v0.2.0/sam_vit_l_0b3195.decoder.quant.onnx
input_size: 1024
max_width: 1024
max_height: 682
