type: yolo11_obb
name: yolo11s-obb-r20240930
display_name: YOLO11s_obb (DOTA-v1.0) Ultralytics
model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.4.4/yolo11s-obb.onnx
nms_threshold: 0.7
confidence_threshold: 0.25
classes:
  - plane
  - ship
  - storage tank
  - baseball diamond
  - tennis court
  - basketball court
  - ground track field
  - harbor
  - bridge
  - large vehicle
  - small vehicle
  - helicopter
  - roundabout
  - soccer ball field
  - swimming pool

