type: yolov6_face
name: yolov6lite_s_face-r20230520
provider: MeiTuan
display_name: YOLOv6Lite_s-Face
model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v0.1.0/yolov6lite_s_face.onnx
iou_threshold: 0.45
conf_threshold: 0.25
classes:
  face:
    - left_eye
    - right_eye
    - nost_tip
    - left_mouth_corner
    - right_mouth_corner