type: ppocr_v4
name: japan_ppocr-r20240803
provider: PaddlePaddle
display_name: japan_PP-OCRv3
det_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v0.2.2/ch_PP-OCRv4_det_infer.onnx
rec_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.4.0/japan_PP-OCRv3_rec_infer.onnx
cls_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v0.2.2/ch_ppocr_mobile_v2.0_cls_infer.onnx
drop_score: 0.5
lang: japan
use_angle_cls: True