type: segment_anything_2_video
name: sam2_hiera_large_video-r20240901
provider: Meta
display_name: Segment Anything 2 Video (Large)
model_cfg: sam2_hiera_l.yaml
device_type: cuda  # cpu, cuda, mps
model_path: https://dl.fbaipublicfiles.com/segment_anything_2/072824/sam2_hiera_large.pt