type: segment_anything
name: segment_anything_vit_b-r20230810
provider: Meta
display_name: Segment Anything (ViT-Base)
encoder_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v0.2.0/sam_vit_b_01ec64.encoder.onnx
decoder_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v0.2.0/sam_vit_b_01ec64.decoder.onnx
input_size: 1024
max_width: 1024
max_height: 682
