type: yolov5_obb
name: yolov5m_obb_csl_dotav20-r20231024
provider: Others
display_name: YOLOv5m_obb (DOTA-v2.0)
model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v1.0.0/yolov5m_obb_csl_dotav20.onnx
stride: 32
iou_threshold: 0.2
conf_threshold: 0.25
classes:
  - plane
  - baseball-diamond
  - bridge
  - ground-track-field
  - small-vehicle
  - large-vehicle
  - ship
  - tennis-court
  - basketball-court
  - storage-tank
  - soccer-ball-field
  - roundabout
  - harbor
  - swimming-pool
  - helicopter
  - container-crane
  - airport
  - helipad
